### ISSUE TITLE
Python release 0.16.0 fails due to failure to build universal2 wheel

### ISSUE THREAD

**Issue by danking** [vortex-data/vortex#1292]
There is insufficient output to diagnose the problem, but the macOS aarch64 and macOS x86_64 builds succeed. It is the last universal2 step which fails. I filed an issue against Maturin-action to ask for some help understanding the error output. AFAICT, other than Rust and Python code changes to Vortex, the main difference between the successful 0.12.0 build and the failing 0.16.0 build are: downgrade from macos-latest to macos-13 and downgrade Python from 3.11 to 3.10. Maybe the macOS change is the cause? Unfortunately, we can't use `macos-latest` anymore because it began prohibiting `pip install`. See [this maturin issue](https://github.com/PyO3/maturin-action/issues/291#issuecomment-2455695273).

- Failing action: https://github.com/spiraldb/vortex/actions/runs/11824325680/job/32946408311
- Previous, successful, action (0.12.0): https://github.com/spiraldb/vortex/actions/runs/11166071447/job/31039891955
- I filed a Maturin issue: https://github.com/PyO3/maturin-action/issues/298

**Comment by robert3005** [comment]
We removed universal2
