### ISSUE TITLE
Add Array::is_some(array_data) for cheaper downcast

### ISSUE THREAD

**Issue by gatesn** [vortex-data/vortex#1377]
Currently we use `SomeArray::try_from(array_data)` all over the place, but this incurs a large cost of creating backtraces.

We do have `array_data.is_encoding(SomeEncoding.id())` but it's a bit clunky.

Proposal is for `SomeArray::is_some(array_data) -> Option<SomeArray>`

**Comment by robert3005** [comment]
as_some? Is_some returning non bool is very weird imho. Is_encoding is only useful if you don’t want to convert the array data to an encoding, ie do some upfront validation

**Comment by gatesn** [comment]
`SomeArray::maybe_from(array_data)`

**Comment by AdamGS** [comment]
WDYT about `as_::<A: Array>()`? no need to resort to `From` like semantics if we don't have `Into` (also a fan of `as_some`).
