### ISSUE TITLE
Align Scalar and DType unions

### ISSUE THREAD

**Issue by gatesn** [vortex-data/vortex#154]
Currently there is Scalar::Primitive, but DType::Int / DType::Float

**Comment by robert3005** [comment]
I guess we split PScalar into Float and Int as well as Primitive into Float/Int

**Comment by gatesn** [comment]
What if we went the other way and added `DType::Primitive(PType)`? Now that we don't do int width inference (i.e. the width is required), it might be simpler to do this and expose the concept of a PType.
