### ISSUE TITLE
Introduce some encodings when encode child of FoRArray

### ISSUE THREAD

**Issue by doki23** [vortex-data/vortex#1659]
If values are not all zeros, it seems that we don't use any encodings to encode the child array -- just minus reference and shift them. We gain no benefits by doing this if I understand correctly.

**Comment by gatesn** [comment]
The recursive compression happens inside the sampling-compressor crate, not in the encode functions of the arrays, e.g. https://github.com/spiraldb/vortex/blob/b5b1095b8e381ecb7e887105a1e203a0656c94ed/vortex-sampling-compressor/src/compressors/for.rs#L61-L64

**Comment by doki23** [comment]
Thank you
