### ISSUE TITLE
Boolean <-> Integer duality

### ISSUE THREAD

**Issue by gatesn** [vortex-data/vortex#441]
We should support converting between strict sorted integers and boolean masks. We may need an array type to go in both directions? 

This could allow us to remove the RoaringUInt array

**Comment by a10y** [comment]
Capturing from slack:

Currently our tableprovider's pushdown is bottlenecked by take(varbin)

![image](https://github.com/user-attachments/assets/b4daf43e-9a36-4b4e-be65-72ac54d00c7d)

DataFusion defers to arrow's filter_bytes function to turn the predicate mask into new ArrayRef:

https://github.com/apache/arrow-rs/blob/920a94470db04722c74b599a227f930946d0da80/arrow-select/src/filter.rs#L660-L689

We want to have our own boolean builder to construct these masks, calculating run lengths, and using that to alternate between slicing/indexing in our implementation of take()

**Comment by danking** [comment]
I think we resolved this in #1327 and #1351. #1327 switched the predicate/mask argument of `filter` to `FilterMask`. I'll close but obviously re-open if there's more work to do!

I profiled the entire TPC-H suite and it seems to be mostly DataFusion stuff.
[_target_release_tpch_benchmark 2024-12-16 11.51 profile.json.gz](https://github.com/user-attachments/files/18154100/_target_release_tpch_benchmark.2024-12-16.11.51.profile.json.gz)

<img width="717" alt="Screenshot 2024-12-16 at 11 58 27 AM" src="https://github.com/user-attachments/assets/09610a34-b51a-4425-9c94-3d97ebef30fc" />
<img width="1919" alt="Screenshot 2024-12-16 at 11 59 23 AM" src="https://github.com/user-attachments/assets/f0797615-9537-4d3c-b87d-f4a31b339f3f" />
