### ISSUE TITLE
Add a RunEndBool encoding

### ISSUE THREAD

**Issue by gatesn** [vortex-data/vortex#456]
This can be used to represent runs in a mask and accelerate the "take" function

**Comment by robert3005** [comment]
Why is this not RunEnd encoding with of BoolArray?

**Comment by gatesn** [comment]
You only need to store the run ends. 

You can say even runs are true, odd runs are false. And insert a zero-length run at the beginning if your array starts with a false value.

**Comment by lwwmanning** [comment]
fixed in #486
