### ISSUE TITLE
Implement Display for ArrayMetadata

### ISSUE THREAD

**Issue by lwwmanning** [vortex-data/vortex#496]
and remove e.g.,

`// TODO(ngates): use Display for metadata` 

https://github.com/spiraldb/vortex/blob/0ad2232/vortex-array/src/tree.rs#L60

**Comment by danking** [comment]
@lwwmanning I'm looking through the good first issue issues and found this.

Do you have an opinion on the format? BoolMetadata at least has a validity, length, and bit_offset. I could do something like "bool ffa1 64 0" where the validity vector is encoded as a hex string?

**Comment by robert3005** [comment]
We should not do this right now. All of array metadata have to be audited for size and it will likely make the display completely different

**Comment by robert3005** [comment]
Should wait for #396

**Comment by robert3005** [comment]
done in #975
