### ISSUE TITLE
RunEnd take doesn't respect validity

### ISSUE THREAD

**Issue by robert3005** [vortex-data/vortex#609]

**Comment by danking** [comment]
We don't break the run on a null. This means the runs and the values do not encode validity. You separately have a validity. The take is currently completely ignoring the validity. Apply the take to the validity first then use that to get values.

**Comment by danking** [comment]
The validity is on the logical indices of the runner array. The validity of the decompressed thing. You have to apply validity to the result of taking from the representation of the run-end's. How do we transform the validity to be valid for the result of taking?

You cannot overwrite the validity of an extant array without knowing which type of array it is.
