### ISSUE TITLE
Python bindings improvements

### ISSUE THREAD

**Issue by robert3005** [vortex-data/vortex#684]
#729 

- [x] Generic Python Array class
- [x] Read Vortex file
- [x] Convert to Numpy/Pandas
- [x] Convert Vortex to Arrow
- [x] Convert Arrow to Vortex
- [x] Compress Vortex array 
- [x] Write to disk (using LayoutWriter) 

---

- [x] Publishing #749
- [x] `rye build` doesn't work #748 (works around https://github.com/PyO3/maturin/issues/2117)

**Comment by danking** [comment]
For Pandas, it appears we could eventually implement an [ExtensionArray](https://pandas.pydata.org/docs/reference/api/pandas.api.extensions.ExtensionArray.html#pandas.api.extensions.ExtensionArray) so that Pandas can operate directly on Vortex arrays.

**Comment by danking** [comment]
@robert3005 Is LayoutWriter a requirement? I'm using `StreamArrayWriter` to write and I'm able to read that again using `StreamArrayReader`. All my round-trip tests have passed thus far.

**Comment by robert3005** [comment]
The StreamArrayReader/Writer are purely for serialising arrays without much framing. LayoutWriter is our logic for writing the file format which involves encoding arrays with prunable layouts
