### ISSUE TITLE
ArrayView could cache cumulativenbuffers

### ISSUE THREAD

**Issue by robert3005** [vortex-data/vortex#786]
In order to access any child of a arrayview we need to slice out it's buffers from the overall structure. Figuring out the buffer counts requires counting number of buffers in children. Since this value is accessed frequently we could give arrayview a slot to cache it

**Comment by a10y** [comment]
[From_Clipboard.speedscope-5.json](https://github.com/user-attachments/files/16966837/From_Clipboard.speedscope-5.json)

SpeedScope output attached

**Comment by gatesn** [comment]
We could also fix up the flatbuffer to make this information easier to extract?
