### ISSUE TITLE
Improve take performance on RunEndArray

### ISSUE THREAD

**Issue by a10y** [vortex-data/vortex#803]
Currently it calls `find_physical_index` in a hot loop. For dense takes, this can be quite a lot of overhead.

![image](https://github.com/user-attachments/assets/f712f902-3c1d-476e-bb63-9a511fa30b08)

**Comment by robert3005** [comment]
FWIW I think we should have search_sorted for numerical arrays that just casts to u64/usize and avoids creating scalars. #795

**Comment by robert3005** [comment]
Another thing would be to update our search_sorted to use the algorithm from latest rust std lib which is said to be 20-30% faster. Doubt we will have comparable speed up but likely there will be some gain

**Comment by a10y** [comment]
This was handled in a combo of #840 + #851
