### ISSUE TITLE
Migrate from Rye to UV

### ISSUE THREAD

**Issue by robert3005** [vortex-data/vortex#977]

**Comment by a10y** [comment]
I think this is currently blocked on https://github.com/astral-sh/uv/issues/5903

The alternative is that we just don't use the scripts

**Comment by robert3005** [comment]
We don’t have any scripts though?

**Comment by a10y** [comment]
Oh I completely missed they got removed in this commit https://github.com/spiraldb/vortex/commit/0c4d74eb7afa359775493dea8d8de77841e727f5#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L31-L33

**Comment by AdamGS** [comment]
We re-introduced one to build docs, I'll talk to @danking and we'll find a solution.
